[Paths] # Paths used by 3DToLD
project_path = "" # Path where your 3D files are located

[Theme]
# Valid values are:
# System, Dark, Light
mode = "System"

[Import_Settings] # Default values for the settings in the "Load File Area"
multicolour      = true
multiple_objects = true
# Valid units are:
# Auto, LDraw, Micrometer, Millimeter, Centimeter, Decimeter, Meter, Inch, Foot
unit  = "Auto"
scale = 1.0
# Possible values are:
# +Z, +Y, -Y
up_axis = "+Z"
custom_3mf_loader = true

    [Import_Settings.Step_Settings]
    tol_linear   = 0.1
    tol_angular  = 0.5
    tol_relative = false

[Metadata] # Defaults for the "Part Metadata" area
name_from_file = true # Get Name from file
name_from_metadata = true # Use name from metadata, if non existend or set to false use filename
default_author       = ""
author_from_metadata = true # If true the default author is also overidden.
default_license = ""

[Convert_To_LDraw_Colours]
# Colour Categories checked by default in the "Convert direct/html colours to LDraw colours" dialog
default_colour_categories = ["LDraw:LDraw Solid Colours", "LDraw:LDraw Internal Common Material Colours"]
# Use default colour categories to convert colours on file import
convert_on_model_load = false